services:
  api:
    build: api
    ports:
      - 3001:80
    volumes:
      - ./api:/src
  ui:
    build: ui
    ports:
      - 3000:80
    volumes:
      - ./ui/app:/src
      - /src/.next
      - /src/node_modules
  db:
    image: postgres:17.0
    environment:
      - POSTGRES_PASSWORD=calice
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  pgdata: