services:
  api:
    build: api
    ports:
      - 9001:80
    volumes:
      - ./api:/src
  db:
    image: postgres:17.0
    environment:
      - POSTGRES_PASSWORD=calice
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  pgdata: