services:
  mongo:
    image: mongo
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: calice
      MONGO_INITDB_ROOT_PASSWORD: calice
      MONGO_INITDB_DATABASE: calice
    ports:
      - 27017
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - sveltekit
      - fastapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:80
      - 3001:3001
  sveltekit:
    build: .
    ports:
      - 3000
      - 3001
    user: node:node
    volumes:
      - /app/.svelte-kit
      - ./src:/app/src
      - ./static:/app/static
      - ./postcss.config.js:/app/postcss.config.js
      - ./svelte.config.js:/app/svelte.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.ts:/app/vite.config.ts
    command: pnpm dev --host=0.0.0.0 --port=3000
  fastapi:
    build:
      dockerfile: api/Dockerfile
      context: .
    ports:
      - 8000
    user: python:python
    volumes:
      - ./api:/app/api
      - ./calice:/app/calice
    environment:
      DATABASE_URL: mongodb://calice:calice@mongo:27017/calice?authSource=admin
    command: uvicorn api.index:app --host=0.0.0.0 --port=8000 --reload