// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.game */
export type GameId = string & { __brand: 'GameId' };

/** Represents the table public.game */
export default interface GameTable {
  id: ColumnType<GameId, GameId | undefined, GameId>;

  title: ColumnType<string, string, string>;
}

export type Game = Selectable<GameTable>;

export type NewGame = Insertable<GameTable>;

export type GameUpdate = Updateable<GameTable>;
