// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as TournamentTable } from './Tournament';

export default interface PublicSchema {
  tournament: TournamentTable;
}
