// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as GameTable } from './Game';
import type { default as RulesetTable } from './Ruleset';
import type { default as TournamentTable } from './Tournament';

export default interface PublicSchema {
  game: GameTable;

  ruleset: RulesetTable;

  tournament: TournamentTable;
}
