// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.ruleset */
export default interface RulesetTable {
  narrative: ColumnType<string, string, string>;
}

export type Ruleset = Selectable<RulesetTable>;

export type NewRuleset = Insertable<RulesetTable>;

export type RulesetUpdate = Updateable<RulesetTable>;
