// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.tournament */
export type TournamentId = string & { __brand: 'public.tournament' };

/** Represents the table public.tournament */
export default interface TournamentTable {
  id: ColumnType<TournamentId, TournamentId | undefined, TournamentId>;

  title: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  startTime: ColumnType<Date, Date | string, Date | string>;

  endTime: ColumnType<Date, Date | string, Date | string>;
}

export type Tournament = Selectable<TournamentTable>;

export type NewTournament = Insertable<TournamentTable>;

export type TournamentUpdate = Updateable<TournamentTable>;
